import { Readiness, ResultsChart } from './Insights.jsx';
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, BookmarkSimple, Check, Clock, FlagCheckered, ListNumbers, ShieldCheck, Stack, X } from '@phosphor-icons/react';
import { QUESTIONS } from '../study-data.js';
import { DELPROV_CONFIG, isExamMode } from '../exam.js';
import { filterReviewAnswers, retryQuestions, reviewCounts } from '../review.js';
import { useStudy } from './context.jsx';
import { AnswerOptions, Button, Empty, IconButton, Modal, ProgressBar, QuestionImage, Ring, ScreenTitle, SectionTitle } from './components.jsx';

const formatTime = n => `${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`;

function Explanation({ q, correct, neutral = false, show = true }) {
  const { l, explainRef } = useStudy();
  return <div role="status" aria-atomic="true">{show&&<div ref={explainRef} className="rounded-[20px] bg-tint p-5"><p className="mb-2 flex items-center gap-2 font-medium text-accent"><Check size={20}/>{neutral?l('Förklaring','Explanation'):correct?l('Precis rätt!','Exactly right!'):l('Ta med dig detta','Remember this')}</p><p className="mb-2 text-sm leading-relaxed"><strong>{l('Rätt svar: ','Correct answer: ')}</strong>{q.options[q.correct]}</p><p className="text-sm leading-relaxed">{q.explanation || q.options[q.correct]}</p></div>}</div>;
}

export function Quiz() {
  const a = useStudy(), {l,quiz} = a;
  const [overview,setOverview] = useState(false);
  const q = a.tq(quiz.questions[quiz.current]), exam = isExamMode(a.mode), answered = quiz.answered!==null;
  const { mainRef } = a;
  const questionIndex = quiz.current;
  useEffect(()=>{mainRef.current?.scrollTo({top:0});},[questionIndex, mainRef]);
  return <>
    <div className="mb-6 flex items-center justify-between gap-3"><IconButton icon={X} label={l('Spara och lämna passet','Save and leave session')} onClick={a.leaveQuiz}/><div className="text-center"><p className="text-xs text-muted">{exam?`${l('Delprov','Sub-test')} ${a.mode}`:a.mode==='focus'?l('Fokuspass','Focus session'):a.mode==='rir'?l('Rätt i rad','Answer streak'):l('Övningspass','Practice session')}</p><p className="mt-1 text-sm font-medium">{quiz.current+1} <span className="text-muted">/ {quiz.questions.length}</span></p></div><IconButton icon={BookmarkSimple} label={a.savedIds.includes(q.id)?l('Ta bort bokmärke','Remove bookmark'):l('Spara frågan','Bookmark question')} active={a.savedIds.includes(q.id)} aria-pressed={a.savedIds.includes(q.id)} onClick={()=>a.toggleSave(q.id)}/></div>
    <ProgressBar value={Math.round(quiz.answers.length/quiz.questions.length*100)} label={l('Besvarade frågor','Answered questions')}/>
    <div className="mt-4 mb-5 flex items-center justify-between text-xs text-muted"><span>{l('FRÅGA','QUESTION')} {String(quiz.current+1).padStart(2,'0')}</span>{exam?<span role="timer" aria-live="off" aria-label={`${l("Tid kvar","Time remaining")}: ${formatTime(a.timeLeft??0)}`} className={`flex items-center gap-1.5 font-mono ${a.timeLeft<300?'text-danger':''}`}><Clock size={16}/>{formatTime(a.timeLeft??0)}</span>:<span>{l('I din egen takt','At your own pace')}</span>}</div>
    <div key={`${quiz.current}-${q.id}`} className="space-y-5">
      {q.image && <QuestionImage src={q.image}/>}
      <h1 className="text-[calc(1.4375rem*var(--text-scale))] leading-[1.3] font-medium tracking-[-.02em]"><span className="sr-only">{l('Fråga','Question')} {quiz.current+1} {l('av','of')} {quiz.questions.length}. </span>{q.question}</h1>
      <AnswerOptions q={q} selected={quiz.answered} reveal={!exam&&answered} disabled={!exam&&answered} onSelect={a.answer}/>
      {!exam&&<Explanation q={q} show={answered} correct={quiz.answered===q.correct}/>}
    </div>
    <div className="quiz-actions mt-5 bg-canvas py-3 safe-bottom">
      {exam ? <><div className="exam-actions flex gap-2"><IconButton icon={ArrowLeft} label={l('Föregående fråga','Previous question')} disabled={quiz.current===0} onClick={()=>a.moveToQuestion(quiz.current-1)}/><Button secondary className="flex-1" onClick={()=>setOverview(true)}><ListNumbers size={19}/>{l('Översikt','Overview')}</Button>{quiz.current<quiz.questions.length-1?<Button onClick={()=>a.moveToQuestion(quiz.current+1)}>{l('Nästa','Next')}<ArrowRight size={18}/></Button>:<Button onClick={a.submitExam}>{l('Lämna in','Submit')}</Button>}</div><button onClick={a.submitExam} className="mt-2 min-h-11 w-full text-sm text-muted underline underline-offset-4">{l('Avsluta och lämna in provet','Finish and submit exam')}</button></>:<Button className="w-full" disabled={!answered} onClick={a.next}>{!answered?l('Välj ett svar','Choose an answer'):quiz.current===quiz.questions.length-1||(a.mode==='rir'&&quiz.answered!==q.correct)?l('Visa resultat','View results'):l('Nästa fråga','Next question')}{answered&&<ArrowRight size={19}/>}</Button>}
    </div>
    {overview&&<Modal title={l('Provöversikt','Exam overview')} onClose={()=>setOverview(false)}><p className="mb-4 text-sm text-muted">{quiz.answers.length}/{quiz.questions.length} {l('besvarade. Du kan ändra dina svar.','answered. You can change your answers.')}</p><div className="exam-overview grid gap-2">{quiz.questions.map((item,i)=><button key={item.id} onClick={()=>{a.moveToQuestion(i);setOverview(false);}} aria-label={`${l('Fråga','Question')} ${i+1}${quiz.answers.some(x=>x.id===item.id)?l(', besvarad',', answered'):l(', obesvarad',', unanswered')}`} aria-current={quiz.current===i?'step':undefined} className={`min-h-11 rounded-xl border text-sm ${quiz.current===i?'border-accent ring-2 ring-accent': 'border-line'} ${quiz.answers.some(x=>x.id===item.id)?'bg-tint text-accent':'bg-soft'}`}>{i+1}</button>)}</div><Button className="mt-5 w-full" onClick={()=>{setOverview(false);a.submitExam();}}>{l('Lämna in prov','Submit exam')}</Button></Modal>}
  </>;
}

export function Exams() {
  const a = useStudy(), {l} = a;
  const [selected,setSelected] = useState(null);
  return <><ScreenTitle eyebrow={l('När du vill testa dig','Put your knowledge to the test')} title={l('Dags för prov','Exam time')}/>
    <Readiness/><ResultsChart/>
    <SectionTitle>{l("Välj ett prov","Choose an exam")}</SectionTitle>
    <div className="mb-7 flex items-center gap-3 rounded-2xl bg-soft p-4"><ShieldCheck size={27} className="shrink-0 text-accent"/><p className="text-sm leading-relaxed">{l('Övningsprov med tidtagning. Facit visas när du lämnar in.','Timed practice exams. Answers appear after you submit.')}</p></div>
    <div className="space-y-4">{[1,2].map(dp=>{const cfg=DELPROV_CONFIG[dp];return <button key={dp} onClick={()=>setSelected(dp)} className="w-full rounded-[28px] border border-line bg-paper p-6 text-left"><div className="mb-7 flex items-center justify-between"><span className="grid size-14 place-items-center rounded-[19px] bg-tint text-accent">{dp===1?<ShieldCheck size={30}/>:<FlagCheckered size={30}/>}</span><span className="font-mono text-4xl text-line">0{dp}</span></div><span className="text-xs font-medium uppercase tracking-[.15em] text-muted">{l('Delprov','Sub-test')} {dp}</span><h2 className="mt-1 text-[calc(1.5625rem*var(--text-scale))] font-medium tracking-tight">{dp===1?l('Säkerhet & beteende','Safety & conduct'):l('Lagstiftning','Legislation')}</h2><div className="mt-5 flex items-center gap-4 border-t border-line pt-4 text-sm text-muted"><span>{cfg.total} {l('frågor','questions')}</span><span className="flex items-center gap-1"><Clock size={16}/>{cfg.time} min</span><span className="ml-auto grid size-9 place-items-center rounded-full bg-accent text-canvas"><ArrowRight size={19}/></span></div></button>;})}</div>
    <p className="mt-5 text-xs leading-relaxed text-muted">{l('Träningsprov i Taxi Teori. Frågorna är inte Trafikverkets officiella provfrågor.','Taxi Teori practice tests. These are not official Trafikverket exam questions.')}</p>
    {selected&&<Modal title={`${l('Starta delprov','Start sub-test')} ${selected}`} onClose={()=>setSelected(null)}><div className="adaptive-row mb-5 flex justify-between rounded-2xl bg-soft p-5">{[[DELPROV_CONFIG[selected].total,l('frågor','questions')],[50,l('minuter','minutes')],[DELPROV_CONFIG[selected].passMark,l('rätt krävs','to pass')]].map(([n,t])=><span key={t} className="text-center"><strong className="block text-2xl font-medium">{n}</strong><span className="text-xs text-muted">{t}</span></span>)}</div><p className="mb-5 text-sm leading-relaxed text-muted">{l(`${DELPROV_CONFIG[selected].total-DELPROV_CONFIG[selected].countedQ} frågor räknas inte i resultatet. Du kan gå tillbaka och ändra svar. Tiden fortsätter även om du lämnar appen.`,`${DELPROV_CONFIG[selected].total-DELPROV_CONFIG[selected].countedQ} questions do not count towards the score. You can go back and change answers. The timer continues when you leave the app.`)}</p><Button className="w-full" onClick={()=>{const dp=selected;setSelected(null);a.startQuiz(dp);}}>{l('Starta provet','Start exam')}<ArrowRight size={18}/></Button></Modal>}
  </>;
}

export function Results() {
  const a = useStudy(), {l,result} = a;
  const [detail,setDetail] = useState(null);
  const rows = filterReviewAnswers(result.answers,a.reviewFilter), counts = reviewCounts(result.answers), retry = retryQuestions(result.answers,a.reviewFilter);
  return <><ScreenTitle eyebrow={l('Passet är klart','Session complete')} title={isExamMode(result.mode)?result.passed?l('Godkänt!','Passed!'):l('Ett steg vidare','One step forward'):l('Bra jobbat!','Nice work!')} action={<IconButton icon={X} label={l('Till startsidan','Go home')} onClick={()=>a.setView('home')}/>}/>
    <section className="adaptive-row mb-6 flex items-center gap-5 rounded-[28px] bg-paper p-6"><Ring value={result.pct} size={112}><span className="text-3xl font-medium">{result.score}<span className="text-lg text-muted">/{result.total}</span></span></Ring><div><h2 className="text-xl font-medium">{result.pct}% {l('rätt','correct')}</h2><p className="mt-2 text-sm text-muted">{isExamMode(result.mode)?l('Poäng på räknade frågor','Score on counted questions'):l('Varje fråga tar dig framåt.','Every question moves you forward.')}</p></div></section>
    {result.expired&&<p role="status" className="mb-4 rounded-2xl bg-soft p-4 text-sm">{l('Tiden tog slut. Dina svar har lämnats in.','Time ran out. Your answers have been submitted.')}</p>}
    {isExamMode(result.mode)&&<p className="mb-5 text-xs leading-relaxed text-muted">{result.unscoredCount} {l('testfrågor räknas inte. Krav för godkänt:','trial questions excluded. Pass mark:')} {DELPROV_CONFIG[result.mode].passMark}/{result.total}.</p>}
    <Button className="mb-7 w-full" disabled={!retry.length} onClick={()=>a.startQuiz('review',retry)}>{retry.length?`${l('Öva igen','Practise again')} · ${retry.length} ${a.questionWord(retry.length)}`:l('Inget att repetera i detta urval','Nothing to repeat in this selection')}<ArrowRight size={18}/></Button>
    <SectionTitle>{l('Dina svar','Your answers')}</SectionTitle><div className="mb-4 adaptive-grid grid grid-cols-2 gap-2">{[['all',l('Alla','All')],['wrong',l('Fel','Wrong')],['unanswered',l('Obesvarade','Unanswered')],['correct',l('Rätt','Correct')]].map(([key,label])=><button key={key} onClick={()=>a.setReviewFilter(key)} aria-pressed={a.reviewFilter===key} className={`min-h-11 rounded-xl border px-3 text-sm ${a.reviewFilter===key?'border-accent bg-tint text-accent':'border-line bg-paper text-muted'}`}>{label} <span className="ml-1 font-mono text-xs">{counts[key]}</span></button>)}</div>
    <div className="divide-y divide-line">{rows.map((r,i)=><button key={r.id} className="flex w-full items-start gap-3 py-4 text-left" onClick={()=>setDetail(i)}><span className={`mt-1 grid size-7 shrink-0 place-items-center rounded-full ${r.chosen===null?'bg-soft text-muted':r.correct?'bg-tint text-accent':'bg-danger-soft text-danger'}`}>{r.chosen===null?<span>–</span>:r.correct?<Check size={16}/>:<X size={16}/>}</span><span className="flex-1 text-sm leading-relaxed"><span className="sr-only">{r.chosen===null?l("Obesvarad. ","Unanswered. "):r.correct?l("Rätt svar. ","Correct answer. "):l("Fel svar. ","Wrong answer. ")}</span>{a.tq(r.q).question}{r.counted===false&&<span className="mt-1 block text-xs text-muted">{l('Testfråga · räknas inte','Trial question · unscored')}</span>}</span><ArrowRight size={16} className="mt-1 shrink-0 text-muted"/></button>)}</div>
    {!rows.length&&<Empty icon={Check} title={l('Inga frågor här','No questions here')} body={l('Välj ett annat filter för att se fler svar.','Select another filter to view more answers.')}/>}
    {detail!==null&&rows[detail]&&<Modal title={`${l('Svar','Answer')} ${detail+1}/${rows.length}`} onClose={()=>setDetail(null)}><ReviewQuestion answer={rows[detail]}/><div className="mt-5 flex justify-between"><IconButton icon={ArrowLeft} label={l('Föregående','Previous')} disabled={detail===0} onClick={()=>setDetail(detail-1)}/><IconButton icon={ArrowRight} label={l('Nästa','Next')} disabled={detail===rows.length-1} onClick={()=>setDetail(detail+1)}/></div></Modal>}
  </>;
}
function ReviewQuestion({answer}) {
  const a = useStudy(), q = a.tq(answer.q);
  return <div key={q.id} className="space-y-4">{q.image&&<QuestionImage src={q.image}/>}<h3 className="text-lg font-medium leading-snug">{q.question}</h3><AnswerOptions q={q} selected={answer.chosen} reveal disabled/><Explanation q={q} neutral/><Button secondary className="w-full" onClick={()=>a.toggleSave(q.id)}><BookmarkSimple size={20}/>{a.savedIds.includes(q.id)?a.l('Ta bort bokmärke','Remove bookmark'):a.l('Spara frågan','Bookmark question')}</Button></div>;
}
export function StudyQuestion() {
  const a = useStudy(), {l} = a, q = a.tq(a.statsQuestion);
  const committed = useRef(false);
  return <Modal title={l('Öva en fråga','Practise a question')} onClose={()=>a.setStatsQuestion(null)}><div className="space-y-4">{q.image&&<QuestionImage src={q.image}/>}<h3 className="text-xl font-medium leading-snug">{q.question}</h3><AnswerOptions q={q} selected={a.statsSelected} reveal={a.statsAnswered} disabled={a.statsAnswered} onSelect={i=>{if(committed.current)return;committed.current=true;a.setStatsSelected(i);a.setStatsAnswered(true);a.saveAnswer(q.id,i===q.correct);if(i===q.correct)a.playPling();else a.playBuzz();}}/><Explanation q={q} show={a.statsAnswered} correct={a.statsSelected===q.correct}/><Button secondary className="w-full" onClick={()=>a.toggleSave(q.id)}><BookmarkSimple size={19}/>{a.savedIds.includes(q.id)?l('Ta bort bokmärke','Remove bookmark'):l('Spara frågan','Bookmark question')}</Button></div></Modal>;
}
export function Daily() {
  const a = useStudy(), {l} = a, q = a.tq(QUESTIONS.find(q=>q.id===a.dailyData.questionId));
  const answered = useRef(a.dailyData.answered);
  return <><ScreenTitle eyebrow={new Date().toLocaleDateString(a.dateLocale,{day:'numeric',month:'long'})} title={l('Dagens fråga','Daily question')} back={{label:l('Tillbaka','Back'),action:()=>a.setView('home')}}/><div className="space-y-5">{q.image&&<QuestionImage src={q.image}/>}<h2 className="text-[calc(1.4375rem*var(--text-scale))] leading-snug font-medium">{q.question}</h2><AnswerOptions q={q} selected={a.dailyData.chosenIdx} reveal={a.dailyData.answered} disabled={a.dailyData.answered} onSelect={i=>{if(answered.current)return;answered.current=true;a.answerDaily(i);}}/><Explanation q={q} show={a.dailyData.answered} correct={a.dailyData.correct}/>{a.dailyData.answered&&<><p className="text-sm text-muted">{l('Kom tillbaka imorgon för en ny fråga.','Come back tomorrow for a new question.')}</p><Button className="w-full" onClick={()=>a.setView('home')}>{l('Klart för idag','Done for today')}<Check size={18}/></Button></>}</div></>;
}
export function Flashcards() {
  const a = useStudy(), {l} = a, q = a.tq(a.flashcards[a.flashIdx]);
  if (!q) return <Empty icon={Stack} title={l('Minneskort','Flashcards')} body={l('Lär dig med fem frågor i taget.','Learn with five questions at a time.')} action={l('Börja','Start')} onClick={a.openFlashcards}/>;
  return <><ScreenTitle title={l('Minneskort','Flashcards')} back={{label:l('Tillbaka','Back'),action:()=>a.setView('utmaningar')}}/><p className="mb-4 text-sm text-muted">{l('Kort','Card')} {a.flashIdx+1}/{a.flashcards.length}</p><div className="space-y-5 rounded-[28px] border border-line bg-paper p-6">{q.image&&<QuestionImage key={q.id} src={q.image}/>}<span className="grid size-12 place-items-center rounded-2xl bg-tint text-accent"><Stack size={25}/></span><h2 data-screen-focus tabIndex={-1} className="text-2xl leading-snug font-medium"><span className="sr-only">{l('Kort','Card')} {a.flashIdx+1}/{a.flashcards.length}. </span>{q.question}</h2><div role="status" aria-atomic="true">{a.flipped?<><p className="font-medium text-accent">{q.options[q.correct]}</p><p className="text-sm leading-relaxed text-muted">{q.explanation}</p></>:<p className="text-sm text-muted">{l('Tänk på svaret innan du vänder.','Think of the answer before you flip.')}</p>}</div><Button className="w-full" secondary onClick={()=>a.setFlipped(!a.flipped)}>{a.flipped?l('Dölj svaret','Hide answer'):l('Vänd kortet','Flip card')}</Button></div><div className="mt-5 flex gap-3"><IconButton icon={ArrowLeft} label={l('Föregående kort','Previous card')} disabled={a.flashIdx===0} onClick={()=>{a.setFlashIdx(a.flashIdx-1);a.setFlipped(false);}}/><Button className="flex-1" onClick={()=>{if(a.flashIdx===a.flashcards.length-1)a.openFlashcards();else{a.setFlashIdx(a.flashIdx+1);a.setFlipped(false);}}}>{a.flashIdx===a.flashcards.length-1?l('Fem nya kort','Five new cards'):l('Nästa kort','Next card')}<ArrowRight size={18}/></Button></div><p className="mt-4 text-xs text-muted">{l('Minneskort påverkar inte din statistik.','Flashcards do not affect your stats.')}</p></>;
}
